### ISSUE TITLE
Screen is not darkened when Popup is displayed

### ISSUE THREAD

**Issue by BlueRaja** [LuckyDucko/Mopups#111]
I'm migrating from Xamarin Rg.Popups to Maui Mopups.

I would expect that when I call `await MopupService.Instance.PushAsync(myPopupPage)`, the background outside the Popup darkens automatically with a semi-transparent overlay, like in the example gifs.  However this doesn't happen. The Popup displays, but the background remains at normal brightness.

My PopupPage isn't doing anything special. In fact the issue repros even on an empty page.

Android API 33
Maui 8.0.7
Mopups 1.3.0

**Comment by MitchBomcanhao** [comment]
aren't you supposed to set your own background color?

**Comment by BlueRaja** [comment]
Yep setting `BackgroundColor="#88000000"` worked. I wasn't aware of this requirement, as it wasn't necessary in `Rg.Popups`.  I wish this were mentioned in the documentation somewhere...
