### ISSUE TITLE
Android back button crashes

### ISSUE THREAD

**Issue by IeuanWalker** [LuckyDucko/Mopups#13]
After i installed the NuGet i've noticed the android device back button is crashing the app.

Navigation bar back button and Navigation.PopAsync are fine, its just the device back button -

https://user-images.githubusercontent.com/6544051/176938616-90bbc6f4-2302-4a57-99d1-cdb956da718a.mp4

Downloaded your source code to try and recreate it using your sample app. Duplicated the main page _(setting the background black)_ and replicated the same issue.

**Comment by LuckyDucko** [comment]
Cheers for this leuan, i thought the releases went too smoothly ;)

I'll get right on it

**Comment by LuckyDucko** [comment]
Believe this bug is squashed (but will wait for PR to be approved, as it involves max's code and a second pair of eyes is good practice), you can test out the changes if you'd like, its a one-liner.

**Comment by IeuanWalker** [comment]
@LuckyDucko awesome thanks, ill give it a test some time today
