### ISSUE TITLE
[iOS] App lifecycle methods (OnResume, OnStart, OnSleep...) are not triggered while popup is open

### ISSUE THREAD

**Issue by santoriny1** [LuckyDucko/Mopups#140]
**Replication Procedure:**

1. Open a popup

2. Try to trigger an App lifecycle method (OnResume, OnStart, OnSleep...) while the popup is open

**Actual behavior :**
The App is not executing the code inside of the App lifecycle methods.

**Expected behavior:**
The App executes the code inside of the App lifecycle methods.

**Additional note**
It is working as expected on Android.

**Comment by Pastajello** [comment]
Do you have any sample for this? I cannot reproduce this issue, it works for iOS and Android for me

**Comment by santoriny1** [comment]
I could solve it adding this code in Platforms/iOS/AppDelegate.cs
```
        public override void OnActivated(UIApplication application)
        {
            (application.ConnectedScenes.AnyObject as UIWindowScene)?.Windows.FirstOrDefault()?.MakeKeyWindow();
            base.OnActivated(application);
        }

        public override void OnResignActivation(UIApplication application)
        {
            (application.ConnectedScenes.AnyObject as UIWindowScene)?.Windows.FirstOrDefault()?.MakeKeyWindow();
            base.OnResignActivation(application);
        }
```
