### ISSUE TITLE
[Housekeeping] Fix CI

### ISSUE THREAD

**Issue by maxkoshevoi** [LuckyDucko/Mopups#17]
Currently [Build](https://github.com/LuckyDucko/Mopups/actions/workflows/build.yml) action is always failing.
Would be nice to fix it

**Comment by LuckyDucko** [comment]
Yeah, that is true, I'll have to look into other maui project to glean how they set theirs up.

**Comment by maxkoshevoi** [comment]
Something like this might do the trick: https://github.com/maxkoshevoi/NureTimetable/blob/maui/.github/workflows/build.yml

**Comment by IeuanWalker** [comment]
@LuckyDucko @maxkoshevoi just did a pipeline for one of my controls - https://github.com/IeuanWalker/Maui.Breadcrumb/tree/master/.github/workflows

The release workflow is triggered when you create a GitHub release, you name the release the version number you want and it will automatically update the NuGet version and upload the NuGet to nuget.org
