### ISSUE TITLE
Sample crashes when opening Popup

### ISSUE THREAD

**Issue by maxkoshevoi** [LuckyDucko/Mopups#2]
When pressing button to open popup, sample app cashes with:

```
Java.Lang.IllegalArgumentException: 
'The style on this component requires your app theme to be Theme.MaterialComponents (or a descendant).'
```

**Comment by LuckyDucko** [comment]
Huh, this is weird, i definitely was able to build it, what did you build yours with?

**Comment by maxkoshevoi** [comment]
Visual Studio 2022 17.2 Preview 1
Android 11

**Comment by LuckyDucko** [comment]
Hey max, i am now catching this using the latest. Its weird how i seemed to fly by without it affecting me for a while? perhaps my tooling was not up to date.

Launching a completely blank page seems to be fine, 
and the issue you are referencing is surrounding the button that is on the page, 

once i remove the button, another seperate issue arises that i will update this comment with when i can.

**Comment by LuckyDucko** [comment]
@maxkoshevoi  this has been all sorted thanks to the hints from @AswinPG
