### ISSUE TITLE
iOS rendering issue

### ISSUE THREAD

**Issue by IeuanWalker** [LuckyDucko/Mopups#21]
iOS doesn't render the popups correctly -

- The popup is cut off at the bottom
- Looks like the background is rendered twice with one having a margin added, so there is a darker inner background

![image](https://user-images.githubusercontent.com/6544051/178936984-cf4a5336-b154-4ff4-8e32-549064a43bc1.png)

**Comment by IeuanWalker** [comment]
@LuckyDucko heres the issue, i cant assign you

**Comment by LuckyDucko** [comment]
@IeuanWalker sorry this weekend was filled, this week your PR and this will be addressed

**Comment by Mous625** [comment]
Hey @LuckyDucko any updates about this issue? Thanks!

**Comment by LuckyDucko** [comment]
@Mous625 yeah sorry about the wait, i'll be honest i've been avoiding doing this so i guess that's todays job ;) wish me luck

**Comment by Mous625** [comment]
Hey thanks for your reply, so from what I'm understanding we need to wait for a fix from the Maui team? This is ofcourse pertaining to the padding of the background dimming view behind the actual content.

**Comment by LuckyDucko** [comment]
Oh the fix is for the stacklayout

I'm still determining whats going on with the double border, as i believe it might be something to do with safe area insets? Honestly not too sure.

**Comment by LuckyDucko** [comment]
I am definitely struggling with this one, I'm having difficulty trying to determine the actual cause, so then I can start googling about how to fix it. 

The fact that I can make a popup larger than the darkened border is what confuses me, as then what is it binding to?

**Comment by LuckyDucko** [comment]
Latest update, As the Community Toolkit popups don't seem to suffer from the same issue, I'm trying to figure out what makes it tick, I might ask one of their devs for some insight into it.

**Comment by Mous625** [comment]
Great, I've used the community toolkit popups however yours do a much better job. Looking forward!

**Comment by Mous625** [comment]
Has there been any progress regarding this, please? TIA.

**Comment by LuckyDucko** [comment]
> Has there been any progress regarding this, please? TIA.

Currently no, sorry i haven't had time to work on any open source work. But do have plans going forward. Just keep holding on, again sorry for the wait

**Comment by LuckyDucko** [comment]
@mous @IeuanWalker 

Stumbled on the solution luckily, will release an update soon just want to make sure it isn't masking other things

**Comment by IeuanWalker** [comment]
@LuckyDucko that's great news, well done :)

**Comment by Mous625** [comment]
Fantastic, good job!

**Comment by LuckyDucko** [comment]
sorted in 1.0.2, cheers guys

**Comment by Mous625** [comment]
Great, the fix looks good thanks. Unfortunately, there is a new issue specific to IOS which makes mopups unusable at the moment. I'm not sure if I am doing something wrong, however I've uploaded a new issue with all the information. Thanks.
