### ISSUE TITLE
iOS Architecture error

### ISSUE THREAD

**Issue by janwiebe-jump** [LuckyDucko/Mopups#30]
Hi,
Thanks for this great plugin!
When building my iOS MAUI app, I get the following warning:
 There was a mismatch between the processor architecture of the project being built "" and the processor architecture of the reference "/Users/runner/.nuget/packages/mopups/1.0.3/lib/net6.0-ios15.4/Mopups.dll", "AMD64".
 Should iOS not have the ARM64 architecture? It looks like this is not the case for Mopups.

Kind regards!

**Comment by LuckyDucko** [comment]
Hey @janwiebe-jump 

This is the first time i've seen an error like this, thanks for bringing it up, I'll investigate

**Comment by LuckyDucko** [comment]
@janwiebe-jump 

Are you using a newer M1 or M2 based Macbook?

**Comment by janwiebe-jump** [comment]
Yes, I'm on a M1 Pro

**Comment by busec0** [comment]
I'm seeing the same issue building from an M1 Mac.

**Comment by busec0** [comment]
Created https://github.com/LuckyDucko/Mopups/pull/32 to address this issue.

**Comment by LuckyDucko** [comment]
Legend @busec0
