### ISSUE TITLE
Android - OnAppering, OnDisappearing not working

### ISSUE THREAD

**Issue by mbilalbenli** [LuckyDucko/Mopups#31]
This functions and event not working. When a pop-ups appear or disappear They are don't be triggered.

     `	public MyPopup()
	{
		InitializeComponent();
		this.Appearing += LoaderState_Appearing;
		this.Disappearing += LoaderState_Disappearing;
	}

	private void LoaderState_Disappearing(object sender, EventArgs e)
	{
		
	}

	private void LoaderState_Appearing(object sender, EventArgs e)
	{
		
	}

	protected override void OnAppearing()
	{
		base.OnAppearing();
	}

	protected override void OnDisappearing()
	{
		base.OnDisappearing();
	}`

Workaround

     `	public MyPopup()
	{
		InitializeComponent();
		MopupService.Instance.Popping += Instance_Popping;
		MopupService.Instance.Pushing += Instance_Pushing;

	}

	private void Instance_Pushing(object sender, Mopups.Events.PopupNavigationEventArgs e)
	{
		if (e.Page is MyPopup)
		{
                        //appering 
                } 
	}

	private void Instance_Popping(object sender, Mopups.Events.PopupNavigationEventArgs e)
    {
        if (e.Page is MyPopup)
        {
                       disappering
        }
    }`

**Comment by LuckyDucko** [comment]
@mbilalbenli 

This is definitely an important one, i'll add it to the list thanks for that bug report

**Comment by LuckyDucko** [comment]
@mbilalbenli 

I realised I added a commit to fix this, but never released, I'll do that ASAP my apologies
