### ISSUE TITLE
Can we make the PopupNavigation PopupStack property static?

### ISSUE THREAD

**Issue by kkppstudios** [LuckyDucko/Mopups#33]
I would like to be able to check the count of the PopupStack by doing something like:

Mopups.Services.PopupNavigation.PopupStack.Count

I want to do this to add a protective check before trying to pop something of an empty stack. The PopupStack property would need to be made static.

Thoughts?

**Comment by LuckyDucko** [comment]
You can currently do 
> MopupService.Instance.PopupStack.Count

Since the IPopupNavigation is a Singleton hidden behind a Lazy<T> it should always be the version you are using. Does this work for you?

**Comment by kkppstudios** [comment]
Ahh that's what I was looking for. I'll try that, thanks!

**Comment by LuckyDucko** [comment]
No worries, glad to help
