### ISSUE TITLE
Exit code 0x80070005 on windows platform

### ISSUE THREAD

**Issue by Laurent0506** [LuckyDucko/Mopups#40]
Hi,
It's working perflectly on Android emulator but crash on Windows platform exit code 0x80070005.
![image](https://user-images.githubusercontent.com/71120618/209463331-aa1b4086-9ae2-4ace-86ef-6e29a76c4d19.png)
If you won't I can upload my test project on Github.

Merry christmas.

**Comment by LuckyDucko** [comment]
your test project would definitely be helpful here

**Comment by LuckyDucko** [comment]
@Laurent0506 Could you provide your test project please

**Comment by Laurent0506** [comment]
@LuckyDucko everything is OK now, thank's. I have upgrade VS to Version 17.5.0 Preview 5.0 and .net runtime 7.0.2 & sdk 7.0.102 Do you my test project anyway ?

**Comment by LuckyDucko** [comment]
@Laurent0506 all good, glad to know its resolved
