### ISSUE TITLE
CloseWhenBackgroundIsClicked=True does not work on iOS

### ISSUE THREAD

**Issue by tranb3r** [LuckyDucko/Mopups#41]
`CloseWhenBackgroundIsClicked=True` does not work on iOS.
Unless you also set `BackgroundInputTransparent=True`, but then the click is passed to the element that is visible, which is probably not what you want to do.

On the sample project:
- the loginPage is ok : `CloseWhenBackgroundIsClicked=True` and `BackgroundInputTransparent=True` (no background visible element).
- the AswinPage is broken : `CloseWhenBackgroundIsClicked=True` and `BackgroundInputTransparent=False` (visible elements in background).

No issue on Android.

Could you please take a look?
Thanks

**Comment by jakob-reesalu** [comment]
Got the same problem here!

**Comment by jpsaccount** [comment]
Got the same problem. Any updates?

**Comment by Sumn3rd** [comment]
Finding the same problem on Windows. 

Interesting enough if you set: CloseWhenBackgroundIsClicked to false; & InputTransparent to true, it allows the clickthrough to background at the cost of losing access to content on the popup. 

Inside version 1.1.0 It would seem that: BackgroundClickedCommand is always null inside popup.cs - meaning the if CanExecute condition is never true, preventing the command to fire but stopping the null exception.

**Comment by LuckyDucko** [comment]
Found a simple fix for iOS which I will add.

In the iOS mopups section, we have the "PopupWindow" file.

This file is used so we can hook and override the HitTest function of a popupwindow, so we can determine if the popupwindow was hit or not. 

When it determines if it should send a background click, I just added in an extra check for CloseWhenBackgroundIsClicked, so it should sort out the iOS one.

Windows I dont have access to a windows computer right now to poke at, but in PopupPageRenderer there is the following screenshot, I would toy around with that, as it is attached to the pointer pressed event.
<img width="552" alt="Screenshot 2023-01-12 at 10 27 44" src="https://user-images.githubusercontent.com/17778102/211939943-0fc94588-53c4-4f06-9538-f8eff3c92f6e.png">

**Comment by LuckyDucko** [comment]
@tranb3r 
@jakob-reesalu 
@jpsaccount 

If you guys want to download the repo, and link Mopups to your app instead of using the nugget, could verify if you believe its a fix for the issue.

**Comment by PaulMDemers** [comment]
I am also experiencing the issue on under MacCatalyst.

**Comment by tranb3r** [comment]
@LuckyDucko 
It now behaves like if `BackgroundInputTransparent` is always `True`, which is probably not what we want, is it?

**Comment by LuckyDucko** [comment]
It does? I'll do some more testing, but i did test and and could confirm there is a difference between the two.

**Comment by tranb3r** [comment]
I've tested the sample AswinPage, on iOS, and when I click on the background, the popup does close now, but the click is propagated to the element behind, even if BackgrouInputTransparent is false.

**Comment by vccosenza** [comment]
someone already mentioned this but the issue exists in Mac catalyst as well. Other than the CloseWhenBackGroundClicked issue, these popups work much nicer than the community toolkit for my apps needs. Could we get a Mac catalyst fix?

**Comment by LuckyDucko** [comment]
@tranb3r 

Give it one more test, I did a more in depth dive.

it turns out that when I perform a a HitTest, if you return null to that hit test, under the hood iOS attempts to find the next ui interact-able element to fire off, which is why the previous fix wasn't working. 

@vccosenza & @PaulMDemers 

I added the same fix to MacCatayst, however, on my computer MacCatalyst seems broken? is it just the sample app that works this way?

**Comment by vccosenza** [comment]
@LuckyDucko  In the latest of the sample app, I am seeing Mac catalyst close instantly after the popup opens. The latest Nuget version I have installed in my project though this is not the case and works really well other than the background close issue

**Comment by tranb3r** [comment]
> @tranb3r
> Give it one more test, I did a more in depth dive.

Yes, it think it works now. Thanks!

**Comment by PaulMDemers** [comment]
Just tested the sample app on Catalyst, the windows do appear and disappear. However they appear to move as soon as the mouse moves and are not waiting for a click.

Click, no mouse move -> shows -> mouse move -> vanishes

**Comment by PaulMDemers** [comment]
I modified the HitTest function in the MacCatalyst PopupWindow HitTest function.

Changed:
formsElement.SendBackgroundClick();

to:
if(uievent?.ButtonMask != 0)
    formsElement.SendBackgroundClick();
    
On line 40, this appears to correct the issue for me.

**Comment by LuckyDucko** [comment]
Thanks guys, sorted on latest release https://github.com/LuckyDucko/Mopups/releases/tag/v1.1.1

**Comment by RichardMarsh** [comment]
Thank you for this!
