### ISSUE TITLE
IOS Issues

### ISSUE THREAD

**Issue by SamJames101** [LuckyDucko/Mopups#44]
Having either no popup shown or a null exception when trying to push a page inside the view model for iOS.

When I inject the MopupService as a singleton into the constructor and use the service like this `await this.popupNavigation.PushAsync(new MyPage());` inside of a MainThread.BeginInvokeOnMainThread I get the error below. I get the same error when using `await MopupService.Instance.PushAsync(new MyPage());`

   at Mopups.Platforms.iOS.PopupPageHandler..ctor()
   at System.Reflection.ConstructorInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)

When I either don't put it inside of a MainThread.BeginInvokeOnMainThread or the old Device.BeginInvokeOnMainThread then no exception but the popup never appears (Running in Viewmodel).

If I use either PushAsync() method in the view itself it only works if it is placed inside of a clicked event. But if it's placed inside of an event listener method that was invoked inside the ViewModel then we see the same error.

I am able to use PushAsync inside the ViewModel for Android.

I am a bit confused. I am using .ConfigureMopups() inside of the mauiProgram and am also using app shell to carry out my other navigation elements.

**Comment by SamJames101** [comment]
Error message points to mopups but I think it is related to something in my own code

**Comment by LuckyDucko** [comment]
If there is still difficulties let me know

**Comment by jBijsterboschNL** [comment]
@SamJames101 & @LuckyDucko, I ran into this issue as well, but a work-around for me was to wrap the MopupService.Instance.PushAsync() in a Dispatcher.Dispatch( ... ).
