### ISSUE TITLE
Version 1.1.1 Throws WinUI error

### ISSUE THREAD

**Issue by DavidPressman** [LuckyDucko/Mopups#47]
After upgrading to today's version 1.1.1, Win UI throws a runtime type initializer error whose inner exception is "Operation not supported on this platform." I am using latest Visual Studio Enterprise stable on up-to-date Windows 11, original release. I have tried both clean/rebuild and then deletion in the affected project of its bin folder and everything in its obj folder except project.assets.json. No change. Reversion to previous Mopups version cures issue. Tried all this twice with identical results.

David Pressman

**Comment by LuckyDucko** [comment]
Cheers david, i did add something experimental into windows, i suspect it may be it.

1.1.0 would be best bet

**Comment by JaredMata** [comment]
Same problem here. I'll be using 1.1.0 as directed but I'm anxious for getting the newer version.

**Comment by LuckyDucko** [comment]
1.1.0 for windows users is the exact same for 1.1.1, this is my bad though, wont happen in the future

**Comment by enisn** [comment]
Same problem here, I can't upgrade to 1.1.1 since it's not working on windows

**Comment by mikaelsundin** [comment]
It seems to start if you add this to csproj file (exist in Mopups sample project)
But i get NotImplementedException for the service on windows instead.

```
  <ItemGroup Condition="$(TargetFramework.Contains('-windows'))">
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.2.221116.1" />
  </ItemGroup>
```

**Comment by FullTimeThinker** [comment]
Any plans to have a fix?  Thanks.

**Comment by juanmalm** [comment]
Same issue here

**Comment by srqdevg** [comment]
The issue is that the symbol WINDOWS is not defined. so none of the Window specific code is included in the build. I figured this out by using JustDecompile to view the source as it sees it and looking at class AppHostBuilderExtensions, none of the Windows handler code is included. I can only presume this is something Microsoft has broken.

**Comment by Bliitze** [comment]
Same issue when upgrading version 1.1.1
This is the following error message: "operation is not supported on this platform" on Windows platform.
