### ISSUE TITLE
How do you pass data when you close a popup?

### ISSUE THREAD

**Issue by gabsamples6** [LuckyDucko/Mopups#55]
Hi
I am probably missing the obvious here,
I have a popup and and  input some data I.E  Person object - Name- Surname  than I close the popup and I need to pass the parameters to the page that called the popup. I noticed that there is a popped  event but is not exposed.

Is there any example on how you can pass data from a pop up to a page when you close the popup?

The only way I can see is using weakreferencemanager from mvvm toolkit but I want to avoid using that to pass data

many thanks for this control!!

**Comment by IeuanWalker** [comment]
@gabsamples6 currently the control doesn't support this out the box, and is something that's in discussion atm.

But you can see how I've added this here - https://github.com/LuckyDucko/Mopups/discussions/8#discussioncomment-3136608

**Comment by psudodev** [comment]
@gabsamples6 how are you passing data? are you using freshMvvm?

**Comment by LuckyDucko** [comment]
With the latest update in the readme, i have made a way to do this internally. 

What you would do is create a popup viewmodel that has an Task<{Your object here}> that represents the data you wish to return.

You can use this building block, along with all the jazz with Mopups prebaked to have it return data to you.
