### ISSUE TITLE
Operation is not supported on this platform error on windows.(C# Markup)

### ISSUE THREAD

**Issue by hilmican-yuksel** [LuckyDucko/Mopups#62]
I updated the project to .net7 and I thought Mopups support the Windows platform. But I get this error.
There are also windows in the "Platforms Supported (Current)" section on the Mopups github page.

![0](https://user-images.githubusercontent.com/89516279/234191172-a75fa201-2c51-4641-9eff-d8fef1924b9a.png)

![1](https://user-images.githubusercontent.com/89516279/234191347-94844af7-b9d1-4539-ba1f-fabc1341a37a.png)

![2](https://user-images.githubusercontent.com/89516279/234191214-86af9968-1a1b-4407-a1c4-2f4b85d2faba.png)

![3](https://user-images.githubusercontent.com/89516279/234191225-5cd54b8c-718d-4982-b6b6-68ff9ba24010.png)

**Comment by srqdevg** [comment]
It's because the Windows methods are never compiled in due to the Windows flag never being set. See [https://github.com/LuckyDucko/Mopups/issues/62](url). Admins need to do a new build and check for this.

**Comment by bakerhillpins** [comment]
Weird, current head of the main branch works - so the windows flag seems to set for me and I've not changed any of that code.

**Comment by carlosduranocon** [comment]
Having the same issue. So if I understand correclty, it is not currently working on windows with .NET 7.0

**Comment by compactdisc-o** [comment]
Downgrading to version 1.1.0 does the trick for me for now

**Comment by douglassimaodev** [comment]
System.PlatformNotSupportedException: 'Operation is not supported on this platform.'

<PackageReference Include="Mopups" Version="1.1.1" />

**Comment by mirceamuresanse** [comment]
With my Windows app:
- using Version 1.1.1 I get:
System.PlatformNotSupportedException: 'Operation is not supported on this platform.'
- using Version 1.1.0 I get:
System.Runtime.InteropServices.COMException: 'Catastrophic failure (0x8000FFFF (E_UNEXPECTED))'

**Comment by mirceamuresanse** [comment]
It works well with Android, but not with Windows, and especially when using this with ReactiveUI

**Comment by LuckyDucko** [comment]
Should be all sorted v1.2.0

Closing and tracking on #74
