### ISSUE TITLE
App not showing the popup and freezing the app on Google Pixel 6 device

### ISSUE THREAD

**Issue by sbkrishnan2506** [LuckyDucko/Mopups#68]
I am working on MAUI application, with the  MopUp implementation and it is working fine in most of the devices and it is not working in the **Google Pixel 6 device**.
The application is frozen. no way to run the application
[MauiMopupsSample-main.zip](https://github.com/LuckyDucko/Mopups/files/11920204/MauiMopupsSample-main.zip)

Please check and resolve the issue, Because of this issue we are holding our release.

**Comment by LuckyDucko** [comment]
Do you have logs? i dont have a google pixel 6

**Comment by sbkrishnan2506** [comment]
Sorry, I do not have logs, I tested with Perfecto device. Look like some issue with Perfecto android devices.
I will update you if any more issue.

Thanks

**Comment by sbkrishnan2506** [comment]
This issue is related to Remove Animation enabled, If we switch off the Remove Animation, it is working fine.
Animation is causing some issue with popup,
