### ISSUE TITLE
Add Animations

### ISSUE THREAD

**Issue by LuckyDucko** [LuckyDucko/Mopups#7]
- investigate 9 dot arrangement
(Tbc)

**Comment by maxkoshevoi** [comment]
MAUI have some buit-in animations. Maybe they could be utilized
https://devblogs.microsoft.com/dotnet/announcing-net-maui-preview-5/#animations

**Comment by LuckyDucko** [comment]
Thanks to @AswinPG this has been solved, we are still using the usual easing animations that we have.

For the built in animations, they seem to be for views you would place IN the page, not the page itself. I believe we should make a seperate issue down the road for that ability.
