### ISSUE TITLE
Android: Sample not working when turning on accessibility features on Samsung devices

### ISSUE THREAD

**Issue by eichbaum** [LuckyDucko/Mopups#77]
When turning on accessibility features on Samsung android devices, popups don't display.
Tested using the current sample.

Settings > Accessibility > Visibility enhancements > Remove animations = turn on
Settings > Accessibility > Visibility enhancements > Reduce transparency and blur = turn on

https://github.com/LuckyDucko/Mopups/assets/131879389/1e224ca4-7929-4adb-af23-702ae4cfab30

**Comment by LuckyDucko** [comment]
Huh, thats unusual. Will keep this open as accessibility is important. Will clause #68 as i believe this is a more general tracker
