### ISSUE TITLE
Windows Support is broken?

### ISSUE THREAD

**Issue by truXton222** [LuckyDucko/Mopups#78]
**Mopups version 1.1.1**

Work fine on Android, but  when i try to push popup on Windows

**await MopupService.Instance.PushAsync(this);**

System.PlatformNotSupportedException: 'Operation is not supported on this platform.'

**Comment by LuckyDucko** [comment]
I do apologise about that, unfortunately i have stepped back from Mobile development in general, and it happened quite soon after i first published this plugin. Just never found the time to catch back up.

I do recommend moving to Mopups 1.1.0 however for windows users

**Comment by LuckyDucko** [comment]
Tracking this on #74
