### ISSUE TITLE
Android: Control (Like Entry) don't work coming back when using Mopups to transition between two pages.

### ISSUE THREAD

**Issue by DigitalNut** [LuckyDucko/Mopups#93]
Use the basic Maui sample app in Visual Studio to test this. Add Mopups NuGet package
1) Create a page (Page1) with an Entry control
2) Create a second page (Page2)
3) Create a basic popup page
4) On page1 setup an action to popup the basic popup (e.g. `MopupService.Instance.PushAsync(BusyPopup, false);`). Also add control/action to go to Page2 after the popup.
5) On Page2, close the popup (`MopupService.Instance.PopAsync(true);`) in `OnAppearing()` . Also add a way to go back to page 1. If using the Maui sample app, this should be done for you

Sample project to reproduced this issue:
[MauiMopupsTest.zip](https://github.com/LuckyDucko/Mopups/files/13310301/MauiMopupsTest.zip)

Now when you run the program, notice that you can input text into the Entry control. Next press the button to go to page 2. This should bring up the popup and when page 2 is loaded the popup should disappear. Now press the button to go back to page 1. Press/touch the Entry control. Notice that the Entry control does not receive focus and no soft keyboard shows up.

The issue is caused by the setting of `DescendantFocusability` property in `HandleAccessibility` (AndroidMopups.cs). 
I noticed that RG.Plugins.Popup does not set this property. The closing of the popup causes this flag to be reset on current page, which is Page2. But the popup was brought up from Page1, which `HandleAccessibility` will set this to `DescendantFocusability.BlockDescendants`. So when you go back to Page1, the Entry control is blocked.

We use this mechanism to bring up a busy popup for long tasks (load resources) than load the next page (as the page can be complex which takes time to load on some phones).

Is this property change required? Can a flag / option be used to control this behavior in the future?

One work around is to close the popup between page changes. Another work around (not modifing Mopups) is to add this code to your page that requires input, then on the OnAppearing() function call function:

Note: Add `#if ANDROID` around function

`using Android.Views;`

```
private void FixMopups()
{
    Page? mainPage = pageToFix; // Application.Current?.MainPage;

    if (mainPage == null)
        return;

    var view = mainPage.Handler?.PlatformView;// as Android.Views.View;
    if (view == null)
        return;

    ((ViewGroup)view).DescendantFocusability = DescendantFocusability.AfterDescendants;
}
```

**Comment by christianrr** [comment]
OMG, it took me hours to figure out what grabs the focus of the Entries in my Maui Android App.
@DigitalNut Many thanks for the hint and providing the workaround, this works well for the moment.

In our App, we have a small permanent visible popup with `CloseWhenBackgroundIsClicked="False" BackgroundColor="Transparent" BackgroundInputTransparent="True"` In this case it does not make sense at all that `DescendantFocusability` is set to BlockDescendants.

Some sort of flag would be a good idea IMO.

**Comment by IeuanWalker** [comment]
@DigitalNut could you put together a small repo, will take a look

**Comment by IeuanWalker** [comment]
@christianrr not quite sure what your use case is here

If you have a popup permanently on top of ur content then people won't be able to interact with the content behind it.

Removing the accessibility handling would mean people using the screen reader on will be able to interact with the stuff behind the popup

But we could relatively easily add a `DisableAccessibilityHandling` flag, just not sure if its necessary

**Comment by christianrr** [comment]
@IeuanWalker We use a popup for a custom (styled) tab bar, which overlays all Shell pages and allows for animations of the tab bar on page transitions. All content pages have set a padding accordingly. As overriding the tab bar appearance of Maui Shell is not an easy one, this "workaround" works perfectly for us. The interaction with page content works well.

Find a repo attached:
[MopupsFocusIssue.zip](https://github.com/LuckyDucko/Mopups/files/13305543/MopupsFocusIssue.zip)

**Comment by DigitalNut** [comment]
@IeuanWalker Sample project is attached in above reported issue.

**Comment by IeuanWalker** [comment]
@DigitalNut this should be fixed once the linked PR is merged and released. 

@christianrr once the linked PR is merged and released, there will be a new property you can add too your popup `DisableAndroidAccessibilityHandling`.

**Comment by LuckyDucko** [comment]
Excellent work @IeuanWalker merged it in. Lets hope it sorts it out
