### ISSUE TITLE
[Ios] [Crash] When popup on screen and app deactivate / activate - there is a crash

### ISSUE THREAD

**Issue by arkadiuszokon** [LuckyDucko/Mopups#95]
**platform:** iOS only
**.net version:** 8.0.0
**plugin version:** 1.2.0
**MauiVersion:** 8.0.0-rc.2.9373

**When:**  displaying popup and then resign activation - move app to background or any other case (like system popup) and then going back to active state.

**What happening:** There is a crash in maui:
`System.InvalidOperationException: Window was already activated at Microsoft.Maui.Controls.Window.Microsoft.Maui.IWindow.Activated() at Microsoft.Maui.LifecycleEvents.AppHostBuilderExtensions.<>c.<OnConfigureLifeCycle>b__2_3(UIApplication app) at Microsoft.Maui.MauiUIApplicationDelegate.<>c__DisplayClass14_0.<OnActivated>b__0(OnActivated del) at Microsoft.Maui.LifecycleEvents.LifecycleEventServiceExtensions.InvokeLifecycleEvents[OnActivated](IServiceProvider services, Action1 action) at Microsoft.Maui.MauiUIApplicationDelegate.OnActivated(UIApplication application) at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName) at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)`

**Potential reason:** I think something is wrong with removing popups from Windows of UIWIndowScene. Look, there is no popups on screen but they remains in Windows NSSet:
![image](https://github.com/LuckyDucko/Mopups/assets/2082525/a3a1d6ac-7d62-4957-9d17-1f8e4b7dfc8f)
Then when iOSLifecycle event from MAUI want to activate/deactivate window the use KeyWindow (https://github.com/dotnet/maui/blob/71687020392deca465f051bc808906836068cc39/src/Core/src/Platform/iOS/UIApplicationExtensions.cs#L48) but the wrong one.

**Workaround:** I found a workaround for that in AppDelegate:

```
public override void OnActivated(UIApplication application)
  {
      (application.ConnectedScenes.AnyObject as UIWindowScene)?.Windows.FirstOrDefault()?.MakeKeyWindow();
      base.OnActivated(application);
  }

  public override void OnResignActivation(UIApplication application)
  {
      (application.ConnectedScenes.AnyObject as UIWindowScene)?.Windows.FirstOrDefault()?.MakeKeyWindow();
      base.OnResignActivation(application);
  }
```

**Comment by christianrr** [comment]
Similar behavior here, but we get a "Window was already deactivated" exception once native permission dialogs appear.

Workaround works for now, many thanks!

**Comment by YGuerin** [comment]
I had the exact same issue. I have an app that have a pop-up used to Get Directions and navigate to the iOS Maps app. When navigating back to my app, the app just crash.

Also, I do confirm that @arkadiuszokon's workaround is working.

**Comment by donatellijl12** [comment]
Thanks for this workaround! I had the same issue and this fixed it for me. The only problem is that the mopup popup was closed whenever the app brought to the foreground. Much better than crashing though!

**Comment by mmilkovski** [comment]
@arkadiuszokon your workaround also helps fix an issue i got today, If app goes in the background while there is popup on screen then OnSleep & OnResume won't fire. Only happens on iOS

Thanks

**Comment by romerotg** [comment]
Yup, that sounds like a MAUI bug, not mopups. I'm getting "Window was already deactivated" when asking for a permission (it shows the native popup)

**Comment by timjamwoo** [comment]
> Yup, that sounds like a MAUI bug, not mopups. I'm getting "Window was already deactivated" when asking for location permission on iOS (it shows the native popup). And the workaround in the original post fixed it

Same for me.

**Comment by MalgorzataPszczolkowska** [comment]
We are still seeing the issue. @LuckyDucko can you confirm version 1.3.1 includes the fix?
