### ISSUE TITLE
Is anyone maintaining this library?

### ISSUE THREAD

**Issue by prok155** [LuckyDucko/Mopups#98]
I'm upgrading my app from Xamarin to .net Maui and I see several issues, like keyboard overlapping popup when entry is used #79, app crashing #95 #97. I used Rg.Plugins.Popup in my Xamarin app and everything worked perfect for me.

@LuckyDucko Is anyone maintaining this library? Or we should look for something else?

**Comment by IeuanWalker** [comment]
@prok155 PRs are being approved you can see that in the commit history.

People are free to submit PRs for any open issues
